version: "3"

services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_talk_react_app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: ["yarn", "start"]
volumes:
  node_modules:
